name: Get data

on:
  workflow_dispatch:

jobs:
  skk-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setting Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Modules
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install beautifulsoup4
          pip install pandas
          pip install urllib3
      - name: Scrape SKK List
        run: |
          python scraper.py
      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
  
  get-items:
    runs-on: ubuntu-latest
    needs: skk-scraper
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setting Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Modules
        run: |
          python -m pip install --upgrade pip
          pip install requests urllib3 pandas
      - name: Scrape Item/Unit Data
        run: python units.py
      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          timestamp=$(TZ='Asia/Jakarta' date +'%a, %F at %H:%M %Z')
          git commit -m "Updated: ${timestamp}" || exit 0
          git push
